language: node_js
node_js:
  - '0.10'
before_script:
  - npm install blanket
  - npm install coveralls
  - npm install mocha-lcov-reporter
script:
  - npm test
  - NODE_ENV=test ./node_modules/.bin/mocha --require blanket -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
